// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Vcode: typeof import('./src/components/vcode/index.vue')['default']
    ViewAside: typeof import('./src/components/viewAside/index.vue')['default']
    ViewHeader: typeof import('./src/components/viewHeader/index.vue')['default']
  }
}
